name: Pull Request Developer Metrics
on:
  pull_request:

jobs:
  Developer_Metrics:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/metrics/action.yml@v0.1
      with:
        github_api_token: ${{ secrets.API_TOKEN_GITHUB }}


