name: Pull Request Developer Metrics
on:
  pull_request:

jobs:
  Developer_Metrics:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shaktitrigent/test_developer_metrics/actions/metrics/action.yml@composite_action1
      with:
        github_api_token: ${{ secrets.API_TOKEN_GITHUB }}
